// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts"
// @generated from file schema.proto (package orec2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file schema.proto.
 */
export declare const file_schema: GenFile;

/**
 * @generated from message orec2.Data
 */
export declare type Data = Message<"orec2.Data"> & {
  /**
   * @generated from field: repeated orec2.Facility facilities = 1;
   */
  facilities: Facility[];

  /**
   * @generated from field: repeated string attribution = 2;
   */
  attribution: string[];
};

/**
 * Describes the message orec2.Data.
 * Use `create(DataSchema)` to create a new message.
 */
export declare const DataSchema: GenMessage<Data>;

/**
 * @generated from message orec2.Facility
 */
export declare type Facility = Message<"orec2.Facility"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2 [json_name = "desc"];
   */
  description: string;

  /**
   * @generated from field: orec2.Source source = 3;
   */
  source?: Source;

  /**
   * @generated from field: string address = 4;
   */
  address: string;

  /**
   * @generated from field: optional orec2.LngLat _lnglat = 5 [json_name = "_lnglat"];
   */
  Lnglat?: LngLat;

  /**
   * raw html
   *
   * @generated from field: string notifications_html = 6;
   */
  notificationsHtml: string;

  /**
   * raw html
   *
   * @generated from field: string special_hours_html = 7;
   */
  specialHoursHtml: string;

  /**
   * @generated from field: repeated orec2.ScheduleGroup schedule_groups = 8;
   */
  scheduleGroups: ScheduleGroup[];

  /**
   * scrape errors
   *
   * @generated from field: repeated string _errors = 9 [json_name = "_errors"];
   */
  Errors: string[];
};

/**
 * Describes the message orec2.Facility.
 * Use `create(FacilitySchema)` to create a new message.
 */
export declare const FacilitySchema: GenMessage<Facility>;

/**
 * @generated from message orec2.Source
 */
export declare type Source = Message<"orec2.Source"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * unix epoch seconds
   *
   * @generated from field: optional google.protobuf.Timestamp _date = 2 [json_name = "_date"];
   */
  Date?: Timestamp;
};

/**
 * Describes the message orec2.Source.
 * Use `create(SourceSchema)` to create a new message.
 */
export declare const SourceSchema: GenMessage<Source>;

/**
 * @generated from message orec2.LngLat
 */
export declare type LngLat = Message<"orec2.LngLat"> & {
  /**
   * @generated from field: float lng = 1;
   */
  lng: number;

  /**
   * @generated from field: float lat = 2;
   */
  lat: number;
};

/**
 * Describes the message orec2.LngLat.
 * Use `create(LngLatSchema)` to create a new message.
 */
export declare const LngLatSchema: GenMessage<LngLat>;

/**
 * @generated from message orec2.ScheduleGroup
 */
export declare type ScheduleGroup = Message<"orec2.ScheduleGroup"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;

  /**
   * for display and filtering, parsed out from the label and normalized, title case
   *
   * @generated from field: string _title = 2 [json_name = "_title"];
   */
  Title: string;

  /**
   * raw html
   *
   * @generated from field: string schedule_changes_html = 3;
   */
  scheduleChangesHtml: string;

  /**
   * @generated from field: repeated orec2.Schedule schedules = 4;
   */
  schedules: Schedule[];
};

/**
 * Describes the message orec2.ScheduleGroup.
 * Use `create(ScheduleGroupSchema)` to create a new message.
 */
export declare const ScheduleGroupSchema: GenMessage<ScheduleGroup>;

/**
 * @generated from message orec2.Schedule
 */
export declare type Schedule = Message<"orec2.Schedule"> & {
  /**
   * @generated from field: string caption = 1;
   */
  caption: string;

  /**
   * for filtering, parsed out from the caption and normalized (i.e., without facility name or date range), lowercase
   *
   * @generated from field: string _name = 2 [json_name = "_name"];
   */
  Name: string;

  /**
   * free-form, but usually the day of the week
   *
   * @generated from field: repeated string days = 3;
   */
  days: string[];

  /**
   * @generated from field: repeated orec2.Schedule.Activity activities = 4;
   */
  activities: Schedule_Activity[];
};

/**
 * Describes the message orec2.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export declare const ScheduleSchema: GenMessage<Schedule>;

/**
 * @generated from message orec2.Schedule.ActivityDay
 */
export declare type Schedule_ActivityDay = Message<"orec2.Schedule.ActivityDay"> & {
  /**
   * @generated from field: repeated orec2.TimeRange times = 1;
   */
  times: TimeRange[];
};

/**
 * Describes the message orec2.Schedule.ActivityDay.
 * Use `create(Schedule_ActivityDaySchema)` to create a new message.
 */
export declare const Schedule_ActivityDaySchema: GenMessage<Schedule_ActivityDay>;

/**
 * @generated from message orec2.Schedule.Activity
 */
export declare type Schedule_Activity = Message<"orec2.Schedule.Activity"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;

  /**
   * for filtering, cleaned up and normalized, lowercase
   *
   * @generated from field: string _name = 2 [json_name = "_name"];
   */
  Name: string;

  /**
   * corresponds to days
   *
   * @generated from field: repeated orec2.Schedule.ActivityDay days = 3;
   */
  days: Schedule_ActivityDay[];
};

/**
 * Describes the message orec2.Schedule.Activity.
 * Use `create(Schedule_ActivitySchema)` to create a new message.
 */
export declare const Schedule_ActivitySchema: GenMessage<Schedule_Activity>;

/**
 * @generated from message orec2.TimeRange
 */
export declare type TimeRange = Message<"orec2.TimeRange"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;

  /**
   * minutes from 00:00, not set if parse error
   *
   * @generated from field: optional int32 _start = 2 [json_name = "_start"];
   */
  Start?: number;

  /**
   * minutes from 00:00, not set if parse error
   *
   * @generated from field: optional int32 _end = 3 [json_name = "_end"];
   */
  End?: number;

  /**
   * sunday = 0, not set if parse error
   *
   * @generated from field: optional orec2.Weekday _wkday = 4 [json_name = "_wkday"];
   */
  Wkday?: Weekday;
};

/**
 * Describes the message orec2.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export declare const TimeRangeSchema: GenMessage<TimeRange>;

/**
 * @generated from enum orec2.Weekday
 */
export enum Weekday {
  /**
   * @generated from enum value: SUNDAY = 0;
   */
  SUNDAY = 0,

  /**
   * @generated from enum value: MONDAY = 1;
   */
  MONDAY = 1,

  /**
   * @generated from enum value: TUESDAY = 2;
   */
  TUESDAY = 2,

  /**
   * @generated from enum value: WEDNESDAY = 3;
   */
  WEDNESDAY = 3,

  /**
   * @generated from enum value: THURSDAY = 4;
   */
  THURSDAY = 4,

  /**
   * @generated from enum value: FRIDAY = 5;
   */
  FRIDAY = 5,

  /**
   * @generated from enum value: SATURDAY = 6;
   */
  SATURDAY = 6,
}

/**
 * Describes the enum orec2.Weekday.
 */
export declare const WeekdaySchema: GenEnum<Weekday>;

