// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weekday int32

const (
	Weekday_SUNDAY    Weekday = 0
	Weekday_MONDAY    Weekday = 1
	Weekday_TUESDAY   Weekday = 2
	Weekday_WEDNESDAY Weekday = 3
	Weekday_THURSDAY  Weekday = 4
	Weekday_FRIDAY    Weekday = 5
	Weekday_SATURDAY  Weekday = 6
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "SUNDAY",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
	}
	Weekday_value = map[string]int32{
		"SUNDAY":    0,
		"MONDAY":    1,
		"TUESDAY":   2,
		"WEDNESDAY": 3,
		"THURSDAY":  4,
		"FRIDAY":    5,
		"SATURDAY":  6,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weekday.Descriptor instead.
func (Weekday) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facilities    []*Facility            `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	Attribution   []string               `protobuf:"bytes,2,rep,name=attribution,proto3" json:"attribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetFacilities() []*Facility {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *Data) GetAttribution() []string {
	if x != nil {
		return x.Attribution
	}
	return nil
}

type Facility struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,json=desc,proto3" json:"description,omitempty"`
	Source            *Source                `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XLnglat           *LngLat                `protobuf:"bytes,5,opt,name=_lnglat,proto3,oneof" json:"_lnglat,omitempty"`
	NotificationsHtml string                 `protobuf:"bytes,6,opt,name=notifications_html,json=notificationsHtml,proto3" json:"notifications_html,omitempty"` // raw html
	SpecialHoursHtml  string                 `protobuf:"bytes,7,opt,name=special_hours_html,json=specialHoursHtml,proto3" json:"special_hours_html,omitempty"`  // raw html
	ScheduleGroups    []*ScheduleGroup       `protobuf:"bytes,8,rep,name=schedule_groups,json=scheduleGroups,proto3" json:"schedule_groups,omitempty"`
	XErrors           []string               `protobuf:"bytes,9,rep,name=_errors,proto3" json:"_errors,omitempty"` // scrape errors
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Facility) Reset() {
	*x = Facility{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facility) ProtoMessage() {}

func (x *Facility) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facility.ProtoReflect.Descriptor instead.
func (*Facility) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Facility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Facility) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Facility) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Facility) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Facility) GetXLnglat() *LngLat {
	if x != nil {
		return x.XLnglat
	}
	return nil
}

func (x *Facility) GetNotificationsHtml() string {
	if x != nil {
		return x.NotificationsHtml
	}
	return ""
}

func (x *Facility) GetSpecialHoursHtml() string {
	if x != nil {
		return x.SpecialHoursHtml
	}
	return ""
}

func (x *Facility) GetScheduleGroups() []*ScheduleGroup {
	if x != nil {
		return x.ScheduleGroups
	}
	return nil
}

func (x *Facility) GetXErrors() []string {
	if x != nil {
		return x.XErrors
	}
	return nil
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XDate         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=_date,proto3,oneof" json:"_date,omitempty"` // unix epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetXDate() *timestamppb.Timestamp {
	if x != nil {
		return x.XDate
	}
	return nil
}

type LngLat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float32                `protobuf:"fixed32,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float32                `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LngLat) Reset() {
	*x = LngLat{}
	mi := &file_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LngLat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LngLat) ProtoMessage() {}

func (x *LngLat) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LngLat.ProtoReflect.Descriptor instead.
func (*LngLat) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *LngLat) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *LngLat) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type ScheduleGroup struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Label               string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XTitle              string                 `protobuf:"bytes,2,opt,name=_title,proto3" json:"_title,omitempty"`                                                        // for display and filtering, parsed out from the label and normalized, title case
	ScheduleChangesHtml string                 `protobuf:"bytes,3,opt,name=schedule_changes_html,json=scheduleChangesHtml,proto3" json:"schedule_changes_html,omitempty"` // raw html
	Schedules           []*Schedule            `protobuf:"bytes,4,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScheduleGroup) Reset() {
	*x = ScheduleGroup{}
	mi := &file_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleGroup) ProtoMessage() {}

func (x *ScheduleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleGroup.ProtoReflect.Descriptor instead.
func (*ScheduleGroup) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleGroup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ScheduleGroup) GetXTitle() string {
	if x != nil {
		return x.XTitle
	}
	return ""
}

func (x *ScheduleGroup) GetScheduleChangesHtml() string {
	if x != nil {
		return x.ScheduleChangesHtml
	}
	return ""
}

func (x *ScheduleGroup) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caption       string                 `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	XName         string                 `protobuf:"bytes,2,opt,name=_name,proto3" json:"_name,omitempty"` // for filtering, parsed out from the caption and normalized (i.e., without facility name or date range), lowercase
	Days          []string               `protobuf:"bytes,3,rep,name=days,proto3" json:"days,omitempty"`   // free-form, but usually the day of the week
	Activities    []*Schedule_Activity   `protobuf:"bytes,4,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

func (x *Schedule) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Schedule) GetXName() string {
	if x != nil {
		return x.XName
	}
	return ""
}

func (x *Schedule) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *Schedule) GetActivities() []*Schedule_Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XStart        *int32                 `protobuf:"varint,2,opt,name=_start,proto3,oneof" json:"_start,omitempty"`                    // minutes from 00:00, not set if parse error
	XEnd          *int32                 `protobuf:"varint,3,opt,name=_end,proto3,oneof" json:"_end,omitempty"`                        // minutes from 00:00, not set if parse error
	XWkday        *Weekday               `protobuf:"varint,4,opt,name=_wkday,proto3,enum=orec2.Weekday,oneof" json:"_wkday,omitempty"` // sunday = 0, not set if parse error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{6}
}

func (x *TimeRange) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimeRange) GetXStart() int32 {
	if x != nil && x.XStart != nil {
		return *x.XStart
	}
	return 0
}

func (x *TimeRange) GetXEnd() int32 {
	if x != nil && x.XEnd != nil {
		return *x.XEnd
	}
	return 0
}

func (x *TimeRange) GetXWkday() Weekday {
	if x != nil && x.XWkday != nil {
		return *x.XWkday
	}
	return Weekday_SUNDAY
}

type Schedule_ActivityDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Times         []*TimeRange           `protobuf:"bytes,1,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule_ActivityDay) Reset() {
	*x = Schedule_ActivityDay{}
	mi := &file_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_ActivityDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_ActivityDay) ProtoMessage() {}

func (x *Schedule_ActivityDay) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_ActivityDay.ProtoReflect.Descriptor instead.
func (*Schedule_ActivityDay) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Schedule_ActivityDay) GetTimes() []*TimeRange {
	if x != nil {
		return x.Times
	}
	return nil
}

type Schedule_Activity struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Label         string                  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XName         string                  `protobuf:"bytes,2,opt,name=_name,proto3" json:"_name,omitempty"` // for filtering, cleaned up and normalized, lowercase
	Days          []*Schedule_ActivityDay `protobuf:"bytes,3,rep,name=days,proto3" json:"days,omitempty"`   // corresponds to days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule_Activity) Reset() {
	*x = Schedule_Activity{}
	mi := &file_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_Activity) ProtoMessage() {}

func (x *Schedule_Activity) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_Activity.ProtoReflect.Descriptor instead.
func (*Schedule_Activity) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Schedule_Activity) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Schedule_Activity) GetXName() string {
	if x != nil {
		return x.XName
	}
	return ""
}

func (x *Schedule_Activity) GetDays() []*Schedule_ActivityDay {
	if x != nil {
		return x.Days
	}
	return nil
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\x05orec2\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x04Data\x12/\n" +
	"\n" +
	"facilities\x18\x01 \x03(\v2\x0f.orec2.FacilityR\n" +
	"facilities\x12 \n" +
	"\vattribution\x18\x02 \x03(\tR\vattribution\"\xea\x02\n" +
	"\bFacility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\vdescription\x18\x02 \x01(\tR\x04desc\x12%\n" +
	"\x06source\x18\x03 \x01(\v2\r.orec2.SourceR\x06source\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12,\n" +
	"\a_lnglat\x18\x05 \x01(\v2\r.orec2.LngLatH\x00R\a_lnglat\x88\x01\x01\x12-\n" +
	"\x12notifications_html\x18\x06 \x01(\tR\x11notificationsHtml\x12,\n" +
	"\x12special_hours_html\x18\a \x01(\tR\x10specialHoursHtml\x12=\n" +
	"\x0fschedule_groups\x18\b \x03(\v2\x14.orec2.ScheduleGroupR\x0escheduleGroups\x12\x18\n" +
	"\a_errors\x18\t \x03(\tR\a_errorsB\n" +
	"\n" +
	"\bX_lnglat\"[\n" +
	"\x06Source\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x125\n" +
	"\x05_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05_date\x88\x01\x01B\b\n" +
	"\x06X_date\",\n" +
	"\x06LngLat\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x02R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x02R\x03lat\"\xa0\x01\n" +
	"\rScheduleGroup\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06_title\x18\x02 \x01(\tR\x06_title\x122\n" +
	"\x15schedule_changes_html\x18\x03 \x01(\tR\x13scheduleChangesHtml\x12-\n" +
	"\tschedules\x18\x04 \x03(\v2\x0f.orec2.ScheduleR\tschedules\"\xa8\x02\n" +
	"\bSchedule\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x14\n" +
	"\x05_name\x18\x02 \x01(\tR\x05_name\x12\x12\n" +
	"\x04days\x18\x03 \x03(\tR\x04days\x128\n" +
	"\n" +
	"activities\x18\x04 \x03(\v2\x18.orec2.Schedule.ActivityR\n" +
	"activities\x1a5\n" +
	"\vActivityDay\x12&\n" +
	"\x05times\x18\x01 \x03(\v2\x10.orec2.TimeRangeR\x05times\x1ag\n" +
	"\bActivity\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05_name\x18\x02 \x01(\tR\x05_name\x12/\n" +
	"\x04days\x18\x03 \x03(\v2\x1b.orec2.Schedule.ActivityDayR\x04days\"\xa3\x01\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\x06_start\x18\x02 \x01(\x05H\x00R\x06_start\x88\x01\x01\x12\x17\n" +
	"\x04_end\x18\x03 \x01(\x05H\x01R\x04_end\x88\x01\x01\x12+\n" +
	"\x06_wkday\x18\x04 \x01(\x0e2\x0e.orec2.WeekdayH\x02R\x06_wkday\x88\x01\x01B\t\n" +
	"\aX_startB\a\n" +
	"\x05X_endB\t\n" +
	"\aX_wkday*e\n" +
	"\aWeekday\x12\n" +
	"\n" +
	"\x06SUNDAY\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x01\x12\v\n" +
	"\aTUESDAY\x10\x02\x12\r\n" +
	"\tWEDNESDAY\x10\x03\x12\f\n" +
	"\bTHURSDAY\x10\x04\x12\n" +
	"\n" +
	"\x06FRIDAY\x10\x05\x12\f\n" +
	"\bSATURDAY\x10\x06b\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schema_proto_goTypes = []any{
	(Weekday)(0),                  // 0: orec2.Weekday
	(*Data)(nil),                  // 1: orec2.Data
	(*Facility)(nil),              // 2: orec2.Facility
	(*Source)(nil),                // 3: orec2.Source
	(*LngLat)(nil),                // 4: orec2.LngLat
	(*ScheduleGroup)(nil),         // 5: orec2.ScheduleGroup
	(*Schedule)(nil),              // 6: orec2.Schedule
	(*TimeRange)(nil),             // 7: orec2.TimeRange
	(*Schedule_ActivityDay)(nil),  // 8: orec2.Schedule.ActivityDay
	(*Schedule_Activity)(nil),     // 9: orec2.Schedule.Activity
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_schema_proto_depIdxs = []int32{
	2,  // 0: orec2.Data.facilities:type_name -> orec2.Facility
	3,  // 1: orec2.Facility.source:type_name -> orec2.Source
	4,  // 2: orec2.Facility._lnglat:type_name -> orec2.LngLat
	5,  // 3: orec2.Facility.schedule_groups:type_name -> orec2.ScheduleGroup
	10, // 4: orec2.Source._date:type_name -> google.protobuf.Timestamp
	6,  // 5: orec2.ScheduleGroup.schedules:type_name -> orec2.Schedule
	9,  // 6: orec2.Schedule.activities:type_name -> orec2.Schedule.Activity
	0,  // 7: orec2.TimeRange._wkday:type_name -> orec2.Weekday
	7,  // 8: orec2.Schedule.ActivityDay.times:type_name -> orec2.TimeRange
	8,  // 9: orec2.Schedule.Activity.days:type_name -> orec2.Schedule.ActivityDay
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	file_schema_proto_msgTypes[1].OneofWrappers = []any{}
	file_schema_proto_msgTypes[2].OneofWrappers = []any{}
	file_schema_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
