// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts"
// @generated from file schema.proto (package orec2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file schema.proto.
 */
export const file_schema = /*@__PURE__*/
  fileDesc("CgxzY2hlbWEucHJvdG8SBW9yZWMyIkAKBERhdGESIwoKZmFjaWxpdGllcxgBIAMoCzIPLm9yZWMyLkZhY2lsaXR5EhMKC2F0dHJpYnV0aW9uGAIgAygJIp4CCghGYWNpbGl0eRIMCgRuYW1lGAEgASgJEhkKC2Rlc2NyaXB0aW9uGAIgASgJUgRkZXNjEh0KBnNvdXJjZRgDIAEoCzINLm9yZWMyLlNvdXJjZRIPCgdhZGRyZXNzGAQgASgJEiwKB19sbmdsYXQYBSABKAsyDS5vcmVjMi5MbmdMYXRIAFIHX2xuZ2xhdIgBARIaChJub3RpZmljYXRpb25zX2h0bWwYBiABKAkSGgoSc3BlY2lhbF9ob3Vyc19odG1sGAcgASgJEi0KD3NjaGVkdWxlX2dyb3VwcxgIIAMoCzIULm9yZWMyLlNjaGVkdWxlR3JvdXASGAoHX2Vycm9ycxgJIAMoCVIHX2Vycm9yc0IKCghYX2xuZ2xhdCJWCgZTb3VyY2USCwoDdXJsGAEgASgJEjUKBV9kYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAUgVfZGF0ZYgBAUIICgZYX2RhdGUiIgoGTG5nTGF0EgsKA2xuZxgBIAEoAhILCgNsYXQYAiABKAIieQoNU2NoZWR1bGVHcm91cBINCgVsYWJlbBgBIAEoCRIWCgZfdGl0bGUYAiABKAlSBl90aXRsZRIdChVzY2hlZHVsZV9jaGFuZ2VzX2h0bWwYAyABKAkSIgoJc2NoZWR1bGVzGAQgAygLMg8ub3JlYzIuU2NoZWR1bGUi+QEKCFNjaGVkdWxlEg8KB2NhcHRpb24YASABKAkSFAoFX25hbWUYAiABKAlSBV9uYW1lEgwKBGRheXMYAyADKAkSLAoKYWN0aXZpdGllcxgEIAMoCzIYLm9yZWMyLlNjaGVkdWxlLkFjdGl2aXR5Gi4KC0FjdGl2aXR5RGF5Eh8KBXRpbWVzGAEgAygLMhAub3JlYzIuVGltZVJhbmdlGloKCEFjdGl2aXR5Eg0KBWxhYmVsGAEgASgJEhQKBV9uYW1lGAIgASgJUgVfbmFtZRIpCgRkYXlzGAMgAygLMhsub3JlYzIuU2NoZWR1bGUuQWN0aXZpdHlEYXkinAEKCVRpbWVSYW5nZRINCgVsYWJlbBgBIAEoCRIbCgZfc3RhcnQYAiABKAVIAFIGX3N0YXJ0iAEBEhcKBF9lbmQYAyABKAVIAVIEX2VuZIgBARIrCgZfd2tkYXkYBCABKA4yDi5vcmVjMi5XZWVrZGF5SAJSBl93a2RheYgBAUIJCgdYX3N0YXJ0QgcKBVhfZW5kQgkKB1hfd2tkYXkqZQoHV2Vla2RheRIKCgZTVU5EQVkQABIKCgZNT05EQVkQARILCgdUVUVTREFZEAISDQoJV0VETkVTREFZEAMSDAoIVEhVUlNEQVkQBBIKCgZGUklEQVkQBRIMCghTQVRVUkRBWRAGYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message orec2.Data.
 * Use `create(DataSchema)` to create a new message.
 */
export const DataSchema = /*@__PURE__*/
  messageDesc(file_schema, 0);

/**
 * Describes the message orec2.Facility.
 * Use `create(FacilitySchema)` to create a new message.
 */
export const FacilitySchema = /*@__PURE__*/
  messageDesc(file_schema, 1);

/**
 * Describes the message orec2.Source.
 * Use `create(SourceSchema)` to create a new message.
 */
export const SourceSchema = /*@__PURE__*/
  messageDesc(file_schema, 2);

/**
 * Describes the message orec2.LngLat.
 * Use `create(LngLatSchema)` to create a new message.
 */
export const LngLatSchema = /*@__PURE__*/
  messageDesc(file_schema, 3);

/**
 * Describes the message orec2.ScheduleGroup.
 * Use `create(ScheduleGroupSchema)` to create a new message.
 */
export const ScheduleGroupSchema = /*@__PURE__*/
  messageDesc(file_schema, 4);

/**
 * Describes the message orec2.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema = /*@__PURE__*/
  messageDesc(file_schema, 5);

/**
 * Describes the message orec2.Schedule.ActivityDay.
 * Use `create(Schedule_ActivityDaySchema)` to create a new message.
 */
export const Schedule_ActivityDaySchema = /*@__PURE__*/
  messageDesc(file_schema, 5, 0);

/**
 * Describes the message orec2.Schedule.Activity.
 * Use `create(Schedule_ActivitySchema)` to create a new message.
 */
export const Schedule_ActivitySchema = /*@__PURE__*/
  messageDesc(file_schema, 5, 1);

/**
 * Describes the message orec2.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export const TimeRangeSchema = /*@__PURE__*/
  messageDesc(file_schema, 6);

/**
 * Describes the enum orec2.Weekday.
 */
export const WeekdaySchema = /*@__PURE__*/
  enumDesc(file_schema, 0);

/**
 * @generated from enum orec2.Weekday
 */
export const Weekday = /*@__PURE__*/
  tsEnum(WeekdaySchema);

